### PR TITLE
Remove cachix from default.nix

### PR DESCRIPTION
**Pull request by d-goncalves**
# Description

Removes cachix from default.nix

### CODE REVIEW

**Review by ReinierMaas — APPROVED** [review]
LGTM! 🚀

**Comment by d-goncalves** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @d-goncalves, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as bcc8df54fa90b0e8f5b7f5affb7b2c10bcc0409b, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/1c01940e-54f1-4a8f-b000-4e1f4b9b95fc?pipeline_id=64e78f0d-3343-4e0a-9edd-133d1cc1d1c7) started.

**Pull request merged**
