### PR TITLE
Automatic Code Formatting

### PR DESCRIPTION
**Pull request by poorlyknitsweater**

### CODE REVIEW

**Comment by poorlyknitsweater** [comment]
Blocked by #14 (To avoid conflicts when rebasing)

**Review by fatho — APPROVED** [review]
LGTM, thanks!

**Comment by poorlyknitsweater** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @poorlyknitsweater, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 7de092e352c587fc0db9ea0da315495cf037eb28, waiting for CI …

**Pull request merged**
