### PR TITLE
Prepare 2.1.0.2 release

### PR DESCRIPTION
**Pull request by ReinierMaas**
Also bump the cabal version bound.

@OpsBotPrime merge!

### CODE REVIEW

**Comment by OpsBotPrime** [comment]
Your merge request has been denied, because merging on Fridays is not recommended. To override this behaviour use the command `merge on Friday`.

**Comment by ReinierMaas** [comment]
@OpsBotPrime merge on Friday!

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @ReinierMaas, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 6b9548cb2e4e293c36ba810eabb26dfa9e2e0af4, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/87351113-b4ac-4ccb-b464-f1ac1ab0fa5f?pipeline_id=6b7c8a95-d066-4875-85aa-fe09746b7530) started.

**Pull request merged**
