### PR TITLE
Use Char instead of Int for code points

### PR DESCRIPTION
**Pull request by poorlyknitsweater**
See #26.

### CODE REVIEW

**Review by fatho — APPROVED** [review]
LGTM! Does it have an impact on the performance, or is it optimized just the same as excepted.

**Comment by poorlyknitsweater** [comment]
@OpsBotPrime merge on friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @poorlyknitsweater, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as bf3ce794867f1ba832705cde2f6583bd9c7168fa, waiting for CI …

**Pull request merged**
