### PR TITLE
Allow using primitive < 0.9 and vector < 0.14

### PR DESCRIPTION
**Pull request by rampion**
Tested with `GHC-9.0.2`

### CODE REVIEW

**Comment by FPtje** [comment]
Thanks for the contribution!

@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @FPtje, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as f4e35b030a7b374c995bae50e39a61bf570b2529, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/957887b1-e079-4dd7-8000-214e75d72023?pipeline_id=1e9c6aaa-7035-495a-a646-ce89bcb5f48d) started.

**Pull request merged**
