### PR TITLE
containsAll functions

### PR DESCRIPTION
**Pull request by jfaure**
including 64 bit accumulator for use with small dictionnaries

### CODE REVIEW

**Comment by ruuda** [comment]
Thank you for taking the time to open a pull request! This is the first external contribution we received, so we are still struggling a bit to figure out a workflow to keep our internal version in sync while still accepting external contributions. We will get back to you shortly.

**Comment by ruuda** [comment]
We just pushed a big update to reconcile our internal version with this repository, and we will pull in the open version into our internal releases going forward, so we are now in a good position to accept external contributions :)

Can you rebase your pull request on top of master?

**Comment by jfaure** [comment]
Have done so,
I'm not sure if we can use the Searcher data for this, should we explicitly pass a case-sensitivity flag ?

**Comment by ruuda** [comment]
> I'm not sure if we can use the Searcher data for this, should we explicitly pass a case-sensitivity flag 

I’m not sure what you mean by this, but the searcher is only produced internally, and it would match case-sensitively at the moment. We could add a case-sensitivity flag to `containsAll`. In that case, non-cases-sensitive matching should use `runLower` instead of `runText`.

**Comment by poorlyknitsweater** [comment]
This will be addressed by #33.

**Pull request closed without merging**
