### PR TITLE
Change ci machine type from e1 to f1

### PR DESCRIPTION
**Pull request by d-goncalves**

### CODE REVIEW

**Comment by d-goncalves** [comment]
@OpsBotPrime merge on friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @d-goncalves, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as be49e2302f15d8dfb5c907e503d01fc2a8c0f479, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/d981005d-421e-48b0-85f4-27e43be1bc1c?pipeline_id=1a17535a-cc8e-4af2-ad45-906801824bdd) started.

**Pull request merged**
