### PR TITLE
Update nix version to 2.10.3 on CI

### PR DESCRIPTION
**Pull request by adrianotm**

### CODE REVIEW

**Review by FPtje — APPROVED** [review]
Thanks!

**Comment by adrianotm** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @adrianotm, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as cc9a926270e8a25ddf14f9a103f1bdbe349f512e, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/b6748969-0d82-4f3a-8275-a67363a6a2e3?pipeline_id=9fe0d52e-21e5-4f97-a938-1c7b29a9ac5e) started.

**Pull request merged**
