### PR TITLE
Update changelog for 2.0.0.0 release

### PR DESCRIPTION
**Pull request by fatho**
Final preparation for the new release. The version in the cabal file has already been updated.

### CODE REVIEW

**Review by FPtje — APPROVED** [review]
LGTM!

**Comment by fatho** [comment]
@OpsBotPrime merge

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @fatho, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 54f85ffc1225ad30ec0754b775f2cb03f084311d, waiting for CI …

**Pull request merged**
